### ISSUE TITLE
Vercel: Error: Setting up fake worker failed: "Cannot find module './pdf.worker.js'

### ISSUE THREAD

**Issue by asontha** [vvanghelue/node-extract-text-from-file#1]
Looped this dependency in to parse the text out of some files. Works great locally but running into this error when deploying on vercel:

```
2022-12-27T00:58:06.553Z	a27e6086-aaef-4e09-bd6d-73fded6d26a6	ERROR	Error: Setting up fake worker failed: "Cannot find module './pdf.worker.js'
Require stack:
- /var/task/node_modules/pdfjs-dist/legacy/build/pdf.js
- /var/task/node_modules/node-extract-text-from-file/index.js
- /var/task/.next/server/pages/api/parse.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/___next_launcher.cjs".
    at /var/task/node_modules/pdfjs-dist/legacy/build/pdf.js:5903:36
2022-12-27T00:58:06.553Z	a27e6086-aaef-4e09-bd6d-73fded6d26a6	ERROR	Error: Setting up fake worker failed: "Cannot find module './pdf.worker.js'
Require stack:
- /var/task/node_modules/pdfjs-dist/legacy/build/pdf.js
- /var/task/node_modules/node-extract-text-from-file/index.js
- /var/task/.next/server/pages/api/parse.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/___next_launcher.cjs".
    at /var/task/node_modules/pdfjs-dist/legacy/build/pdf.js:5903:36
RequestId: a27e6086-aaef-4e09-bd6d-73fded6d26a6 Error: Runtime exited with error: exit status 1
Runtime.ExitError
END RequestId: a27e6086-aaef-4e09-bd6d-73fded6d26a6
```

Any idea what's going on? I saw in the source code you tried setting `// pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;` but you have it commented out.

**Comment by asontha** [comment]
Ended up pulling the implementation locally and then migrating it from `pdfjs-dist` to `pdf-parse`. Seems to be working well and `pdf-parse` is also much cleaner to use and it's dependencies are much much smaller.
